[package]
name = "firm_netter"
version = "0.1.7"
edition = "2024"
description = "测试，请勿使用！"
repository = "https://github.com/fghdfjhgj/lib_rust"
documentation = "https://github.com/fghdfjhgj/lib_rust/blob/main/README.md"
license = "Apache-2.0"
[lib]
#rclib
crate-type = ["cdylib","rlib","staticlib"]



[dependencies]
#rustls-tls or native-tls
reqwest = { version = "0.12.12", features = ["blocking", "json", "stream", "native-tls"] }
serde = { version = "1.0.217", features = ["derive"] }
encoding_rs = "0.8.35"

[build-dependencies]
cbindgen = "0.28.0"



