[package]
name = "t3_lib_rust"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
[lib]
crate-type = ["cdylib"]



[dependencies]

reqwest = { version = "0.12.12" ,features = ["blocking"] }
diesel = { version = "2.0.0", features = ["postgres"] }
dotenv = "0.15.0"
libc = "0.2.169"

[build-dependencies]
