[package]
name = "firm_netter"
version = "0.1.9"
edition = "2024"
description = "测试，请勿使用！"
repository = "https://github.com/fghdfjhgj/lib_rust"
documentation = "https://github.com/fghdfjhgj/lib_rust/blob/main/README.md"
license = "Apache-2.0"
[lib]
#rclib
crate-type = ["cdylib","rlib","staticlib"]



[dependencies]
#rustls-tls or native-tls
reqwest = { version = "0.12.15", features = ["blocking", "json", "stream", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
encoding_rs = "0.8.35"
crossbeam = "0.8.4"
rayon = "1.10.0"
once_cell = "1.21.3"
memmap2 = "0.9.5"
percent-encoding = "2.3.1"

[build-dependencies]
cbindgen = "0.28.0"



