[package]
name = "t3_lib_rust"
version = "0.1.7"
edition = "2021"
description = "测试，请勿使用！"
repository = "https://github.com/fghdfjhgj/lib_rust"
documentation = "https://github.com/fghdfjhgj/lib_rust/blob/main/README.md"
license = "Apache-2.0"
[lib]
crate-type = ["cdylib","rlib","staticlib"]



[dependencies]

reqwest = { version = "0.12.12" , features = ["blocking", "json","stream"] }
diesel = { version = "2.0.0", features = ["postgres"] }
dotenv = "0.15.0"
libc = "0.2.169"
serde = { version = "1.0.217", features = ["derive"] }
serde_json= "1.0.79"
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
encoding_rs = "0.8"

[build-dependencies]
cbindgen = "0.28.0"